### PR TITLE
Implement L Block

### PR DESCRIPTION
**Pull request by nyghtly-derek**
- Create `Offset` helper struct, combined with new compenent `BlockOffsets` to define block shape via set of offsets from position
- Refactor game map to be a multi-dimensional array that tracks inactive blocks
- Create `Coordinates` helper struct to interface with game map
- Implement a number of helper functions throughout, general refactoring

Todo:
- Define different types of blocks via a bunch of `const [Offset; 4]` variables that live in some new file
- Refactor block spawner to accept these constants when creating new blocks
- Before moving left or right, check GameMap for inactive blocks that are in the way

Note: 
- In order to implement spinning blocks, a match statement could be used that converts a `BlockOffset` into it's next iteration. 

For example the L blocks starts as...

0, 0
0, -1
0, -2
1, 0

then spins to become...

0, 0
0, -1
1, -1
2, -1

### CODE REVIEW

**Comment by robert-blankenship** [comment]
Looks good! Getting some build errors though:

```
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> src/sys/piston_wrap.rs:65:32
   |
65 | fn clear_window(graphics: &mut piston_window::G2d) {
   |                                ^^^^^^^^^^^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> src/sys/piston_wrap.rs:74:14
   |
74 |     context: piston_window::context::Context,
   |              ^^^^^^^^^^^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> src/sys/piston_wrap.rs:75:20
   |
75 |     graphics: &mut piston_window::G2d,
   |                    ^^^^^^^^^^^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> src/sys/spawn.rs:36:62
   |
36 | fn spawn(updater: &Read<LazyUpdate>, entities: &Entities) -> specs::Entity {
   |                                                              ^^^^^

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `double-tetris`.

To learn more, run the command again with --verbose.
```

**Comment by nyghtly-derek** [comment]
Hm that's interesting, perhaps you're using an older version of Rust than I
am. Can you try to update? And maybe there's someway to indicate the rust
version number required as part of the cargo project.

- Derek

**Comment by robert-blankenship** [comment]
Hm okay:
```
[robert-blankenship@roberts-mbp-2 tetris-with-a-twist]# cargo --version
cargo 1.27.0 (1e95190e5 2018-05-27)
```

**Comment by robert-blankenship** [comment]
Thanks! Working now (updated to 1.33)

**Comment by robert-blankenship** [comment]
Merging now, 👍

**Pull request merged**
